version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "db_vol:/var/lib/mysql"
    networks:
      - my_network
    restart: always
    env_file: .env

  # wordpress:
  #   build: requirements/wordpress/
  #   container_name: wordpress
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - "wordpress_vol:/var/www/html/wordpress"
  #   networks:
  #     - my_network
  #   restart: always
  #   env_file: .env

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "wordpress_vol:/var/www/html/wordpress"
    networks:
      - my_network
    restart: always

networks:
  my_network:

volumes:
  wordpress_vol:
  db_vol: