version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - "db_vol:/var/lib/mysql"
    networks:
      - my_network
    restart: always
    env_file: .env

  wordpress:
    build: requirements/wordpress/
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - "wordpress_vol:/var/www/html/wordpress"
    networks:
      - my_network
    restart: always
    env_file: .env

  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - "wordpress_vol:/var/www/html/wordpress"
    networks:
      - my_network
    restart: always

networks:
  my_network:

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mnies/data/wordpress
  db_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mnies/data/db